### ISSUE TITLE
Class-dump with Swift binaries

### ISSUE THREAD

**Issue by haniag** [nygard/class-dump#51]
Will class-dump be updated to work on Swift binaries? I am currently getting this error "Error: Cannot find offset for address 0x28000000010048d8 in stringAtAddress:" when trying. Thanks.

**Comment by w0lfschild** [comment]
Same issue here.

**Comment by lemonmojo** [comment]
+1

**Comment by subtleGradient** [comment]
I'm getting:

> 2015-08-19 13:09:30.836 class-dump[97205:543522] *** Assertion failure in -[CDObjectiveC2Processor loadMethodsAtAddress:extendedMethodTypesCursor:], /Users/aylott/Downloads/class-dump-master/Source/CDObjectiveC2Processor.m:392
> 2015-08-19 13:09:30.838 class-dump[97205:543522] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [cursor offset] != 0'

**Comment by 0xced** [comment]
You can try my `swift-binaries` branch at https://github.com/0xced/class-dump/tree/swift-binaries
It’s not complete but it doesn’t crash.

**Comment by hexploitable** [comment]
@0xced I also get the error for your fork.
```
./class-dump Payload/swiftNil.app/swiftNil
2016-04-08 15:22:28.758 class-dump[6995:177308] Error: Cannot find offset for address 0xc000000001000076 in stringAtAddress:
```
Do you have a compiled build that you could perhaps add to the "releases" of your repo?

- Grant

**Comment by pavm035** [comment]
Same issue here

**Comment by i42kalran** [comment]
Same here

`class-dump[2871:69688] Error: Cannot find offset for address 0x080016a1 in stringAtAddress:`

**Comment by eggswift** [comment]
Same issue here. How to fix it~

**Comment by lylh** [comment]
Same issue here 
`class-dump[10230:200845] Error: Cannot find offset for address 0x2c00142f in stringAtAddress`

**Comment by hoangpx** [comment]
same here, pls update

**Comment by altimac** [comment]
class-dump[2085:287836] Error: Cannot find offset for address 0x7800000000003f2f in stringAtAddress:

Pretty Please?

**Comment by sunhongyue4500** [comment]
same issue. class-dump[18198:1859074] Error: Cannot find offset for address 0xd00000000101a176 in stringAtAddress. how to fix.

**Comment by dimosz** [comment]
same issue. how to fix?

**Comment by huang1988519** [comment]
same issue.  no answer?

**Comment by jonbho** [comment]
I think the problem is that the Mach-O parsers is getting out of sync in a previous class, thus the string address it reads is wrong (in an address like 0xd00000000101a176, the 0xD0 at the beginning comes from the next field). I'm trying to debug the issue and may create a fork/pull-request if I can fix the issue. I'm getting the issue when trying to class dump IDEPegasusSourceEditor from Xcode 9 beta 2.

**Comment by jonbho** [comment]
Yes, indeed, the sync loss is due to the class data address being off by one, since it's the convention for Swift classes. The change in this pull request fixes this: [https://github.com/nygard/class-dump/pull/43/files](https://github.com/nygard/class-dump/pull/43/files). Still, changing just this still shows other things missing when dumping Swift code. I'm going to fork 0xced's swift-binaries fork, which is supposed to be focusing on Swift support, and send a pull request to fix just this.

**Comment by jonbho** [comment]
Duh, ignore all the above. The commit on October 2, 2015 by nygard already fixed the issue [(link to that commit)](https://github.com/nygard/class-dump/commit/7acf1f00a03a219388a1d19d66edaa954c0be3a5). Just download any version of the code after that. There are many other things to be done to fully support Swift, but this is not an issue any more.

**Comment by gerchicov-bp** [comment]
@jonbho downloaded the last sources (June 5, 2017) - the same problem

**Comment by Tim15** [comment]
I've built `class-dump` from the most recent source (Jun 5, 2017), but I still get the issue:

```
2018-08-07 16:46:53.794 class-dump[9528:51105] Error: Cannot find offset for address 0x300000000100146d in stringAtAddress:
```

@nygard This is a great tool, would be even better if it worked for Swift. Many thanks!

**Comment by jkryanchou** [comment]
Is there any solution on dumping the swift binary?

**Comment by nygard** [comment]
I don't get any of these errors on any of the apps/frameworks that use Swift on my system.
