### ISSUE TITLE
Running class-dump on XCode 8.2.1's generates a method with an CDUnknownBlockType argument

### ISSUE THREAD

**Issue by TeresaP** [nygard/class-dump#71]
When I run class-dump on XCode 8.2.1's /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework file, it generates this in XCUIElement.h:

`- (void)_dispatchEvent:(id)arg1 block:(CDUnknownBlockType)arg2;`

Is this expected? When I try to use it in my project, it complains: "Expected a type".

**Comment by saagarjha** [comment]
Yes, this is expected behavior, since class-dump cannot identify the type of the argument. What it does know is that it is some kind of block; however, it can't tell you the type and parameters of it. If you don't need that parameter, just replace `CDUnknownBlockType` with `id`. Otherwise, you'll have to do a kind of guess-and-check by trying to figure out the number of parameters to the closure and seeing if it crashes at runtime.

**Comment by malhal** [comment]
You can use Hopper to see the number of params and figure them out too by the methods called on them.

**Comment by saagarjha** [comment]
Or, if you're able to run LLDB, break at the top of the method and try printing $arg1, $arg2, etc.
